### ISSUE TITLE
Feature Request: IOS 11

### ISSUE THREAD

**Issue by akeslo** [CoreKit/iconer#4]
Can you please update this to support IOS 11? There is a new 1024x1024 icon.

Thanks!

**Comment by tib** [comment]
Yes, i'll & also this repository is going to be part of the [CoreKit](https://github.com/CoreKit) tools. I'll do the necessary changes during the next week. ;)

**Comment by tib** [comment]
Version 0.4.2 is released with the support for the new iOS11 marketing icon.

```bash
brew install corekit/brew/iconer
```

Note: first you should remove the previous versions & taps if you have any.

```bash
brew uninstall iconer --force
brew untap tib/tap
```
